### ISSUE TITLE
fail to build

### ISSUE THREAD

**Issue by zyctinker** [ARMmbed/dapjs#75]
Hi,
You guys mentioned in readme.md that Gulp is used as a task runner to build the project. But I can't find gulpfile.js in this program. Besides, I failed to run `npm run build` to build this program. The logs are as follow:
`
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle dapjs@2.2.0~prebuild: dapjs@2.2.0
6 info lifecycle dapjs@2.2.0~build: dapjs@2.2.0
7 verbose lifecycle dapjs@2.2.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle dapjs@2.2.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\coding\dapjs\node_modules\.bin;C:\Users\tinker\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\tinker\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\Git\cmd;C:\WINDOWS\System32\OpenSSH;C:\Program Files\nodejs;C:\ProgramData\chocolatey\bin;C:\Python38;C:\Users\tinker\AppData\Local\Programs\Python\Python38\Scripts;C:\Users\tinker\AppData\Local\Programs\Python\Python38;C:\Users\tinker\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Bandizip;D:\Programs\Microsoft VS Code\bin;C:\Users\tinker\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle dapjs@2.2.0~build: CWD: D:\coding\dapjs
10 silly lifecycle dapjs@2.2.0~build: Args: [ '/d /s /c', 'rollup -c && typedoc src' ]
11 silly lifecycle dapjs@2.2.0~build: Returned: code: 1  signal: null
12 info lifecycle dapjs@2.2.0~build: Failed to exec build script
13 verbose stack Error: dapjs@2.2.0 build: `rollup -c && typedoc src`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid dapjs@2.2.0
15 verbose cwd D:\coding\dapjs
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error dapjs@2.2.0 build: `rollup -c && typedoc src`
22 error Exit status 1
23 error Failed at the dapjs@2.2.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`
Could anyone help me? Thanks.

**Comment by thegecko** [comment]
Try node 10

**Comment by zyctinker** [comment]
> Try node 10

Hi gecko,
I reinstalled node v10.22 but it still not worked.
`
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.14.6
3 info using node@v10.22.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle dapjs@2.2.0~prebuild: dapjs@2.2.0
6 info lifecycle dapjs@2.2.0~build: dapjs@2.2.0
7 verbose lifecycle dapjs@2.2.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle dapjs@2.2.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\coding\dapjs\node_modules\.bin;C:\Users\tinker\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\tinker\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\Git\cmd;C:\WINDOWS\System32\OpenSSH;C:\ProgramData\chocolatey\bin;C:\Python38;C:\Program Files\nodejs;C:\Users\tinker\AppData\Local\Programs\Python\Python38\Scripts;C:\Users\tinker\AppData\Local\Programs\Python\Python38;C:\Users\tinker\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Bandizip;D:\Programs\Microsoft VS Code\bin;C:\Users\tinker\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle dapjs@2.2.0~build: CWD: D:\coding\dapjs
10 silly lifecycle dapjs@2.2.0~build: Args: [ '/d /s /c', 'rollup -c && typedoc src' ]
11 silly lifecycle dapjs@2.2.0~build: Returned: code: 1  signal: null
12 info lifecycle dapjs@2.2.0~build: Failed to exec build script
13 verbose stack Error: dapjs@2.2.0 build: `rollup -c && typedoc src`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid dapjs@2.2.0
15 verbose cwd D:\coding\dapjs
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v10.22.0
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error dapjs@2.2.0 build: `rollup -c && typedoc src`
22 error Exit status 1
23 error Failed at the dapjs@2.2.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

`
